//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NADashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d
    {
        public string dvid { get; set; }
        public string dsid { get; set; }
        public string ds { get; set; }
    
        public virtual dv dv { get; set; }
    }
}
