//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NADashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NationalAccountsEntities : DbContext
    {
        public NationalAccountsEntities()
            : base("name=NationalAccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<d> ds { get; set; }
        public virtual DbSet<dv> dvs { get; set; }
        public virtual DbSet<pv> pvs { get; set; }
        public virtual DbSet<Year> Years { get; set; }
    
        public virtual ObjectResult<getCropYearly_Result> getCropYearly(Nullable<int> cropid, Nullable<int> level, string id)
        {
            var cropidParameter = cropid.HasValue ?
                new ObjectParameter("cropid", cropid) :
                new ObjectParameter("cropid", typeof(int));
    
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCropYearly_Result>("getCropYearly", cropidParameter, levelParameter, idParameter);
        }
    
        public virtual ObjectResult<getCards_Result> getCards(Nullable<int> cropid, string year, Nullable<int> level, string id)
        {
            var cropidParameter = cropid.HasValue ?
                new ObjectParameter("cropid", cropid) :
                new ObjectParameter("cropid", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCards_Result>("getCards", cropidParameter, yearParameter, levelParameter, idParameter);
        }
    
        public virtual ObjectResult<getCropdata_Result> getCropdata(string pvid, string dvid, string dsid, string year, Nullable<int> cropid)
        {
            var pvidParameter = pvid != null ?
                new ObjectParameter("pvid", pvid) :
                new ObjectParameter("pvid", typeof(string));
    
            var dvidParameter = dvid != null ?
                new ObjectParameter("dvid", dvid) :
                new ObjectParameter("dvid", typeof(string));
    
            var dsidParameter = dsid != null ?
                new ObjectParameter("dsid", dsid) :
                new ObjectParameter("dsid", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var cropidParameter = cropid.HasValue ?
                new ObjectParameter("cropid", cropid) :
                new ObjectParameter("cropid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCropdata_Result>("getCropdata", pvidParameter, dvidParameter, dsidParameter, yearParameter, cropidParameter);
        }
    
        public virtual ObjectResult<getCropMap_Result> getCropMap(Nullable<int> cropid, Nullable<int> level, string id, string year)
        {
            var cropidParameter = cropid.HasValue ?
                new ObjectParameter("cropid", cropid) :
                new ObjectParameter("cropid", typeof(int));
    
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCropMap_Result>("getCropMap", cropidParameter, levelParameter, idParameter, yearParameter);
        }
    
        public virtual ObjectResult<getCrops_Result> getCrops()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCrops_Result>("getCrops");
        }
    
        public virtual ObjectResult<WorldCropMap_Result> WorldCropMap(string year, Nullable<int> crop, string country)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var cropParameter = crop.HasValue ?
                new ObjectParameter("crop", crop) :
                new ObjectParameter("crop", typeof(int));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WorldCropMap_Result>("WorldCropMap", yearParameter, cropParameter, countryParameter);
        }
    
        public virtual ObjectResult<getCropHierarchyWise_Result> getCropHierarchyWise(Nullable<int> cropid, string year)
        {
            var cropidParameter = cropid.HasValue ?
                new ObjectParameter("cropid", cropid) :
                new ObjectParameter("cropid", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCropHierarchyWise_Result>("getCropHierarchyWise", cropidParameter, yearParameter);
        }
    
        public virtual ObjectResult<getSimpleCards_Result> getSimpleCards(Nullable<int> cropid, string year, Nullable<int> level, string id)
        {
            var cropidParameter = cropid.HasValue ?
                new ObjectParameter("cropid", cropid) :
                new ObjectParameter("cropid", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSimpleCards_Result>("getSimpleCards", cropidParameter, yearParameter, levelParameter, idParameter);
        }
    
        public virtual ObjectResult<getGDP_Result> getGDP(Nullable<int> months, string currency, string price, string output, Nullable<int> fyear)
        {
            var monthsParameter = months.HasValue ?
                new ObjectParameter("months", months) :
                new ObjectParameter("months", typeof(int));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("currency", currency) :
                new ObjectParameter("currency", typeof(string));
    
            var priceParameter = price != null ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(string));
    
            var outputParameter = output != null ?
                new ObjectParameter("output", output) :
                new ObjectParameter("output", typeof(string));
    
            var fyearParameter = fyear.HasValue ?
                new ObjectParameter("fyear", fyear) :
                new ObjectParameter("fyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGDP_Result>("getGDP", monthsParameter, currencyParameter, priceParameter, outputParameter, fyearParameter);
        }
    
        public virtual ObjectResult<getGDPbreakdown_Result> getGDPbreakdown(Nullable<int> months, string currency, string price, string output, Nullable<int> fyear)
        {
            var monthsParameter = months.HasValue ?
                new ObjectParameter("months", months) :
                new ObjectParameter("months", typeof(int));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("currency", currency) :
                new ObjectParameter("currency", typeof(string));
    
            var priceParameter = price != null ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(string));
    
            var outputParameter = output != null ?
                new ObjectParameter("output", output) :
                new ObjectParameter("output", typeof(string));
    
            var fyearParameter = fyear.HasValue ?
                new ObjectParameter("fyear", fyear) :
                new ObjectParameter("fyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGDPbreakdown_Result>("getGDPbreakdown", monthsParameter, currencyParameter, priceParameter, outputParameter, fyearParameter);
        }
    
        public virtual ObjectResult<getGrowths_Result> getGrowths(Nullable<int> months, string currency, string price, Nullable<int> from, Nullable<int> to)
        {
            var monthsParameter = months.HasValue ?
                new ObjectParameter("months", months) :
                new ObjectParameter("months", typeof(int));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("currency", currency) :
                new ObjectParameter("currency", typeof(string));
    
            var priceParameter = price != null ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(string));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGrowths_Result>("getGrowths", monthsParameter, currencyParameter, priceParameter, fromParameter, toParameter);
        }
    
        public virtual ObjectResult<getTaxes_Result> getTaxes(Nullable<int> year, string sector, string subsector, string title)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var sectorParameter = sector != null ?
                new ObjectParameter("sector", sector) :
                new ObjectParameter("sector", typeof(string));
    
            var subsectorParameter = subsector != null ?
                new ObjectParameter("subsector", subsector) :
                new ObjectParameter("subsector", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTaxes_Result>("getTaxes", yearParameter, sectorParameter, subsectorParameter, titleParameter);
        }
    
        public virtual ObjectResult<getWorldYear_Result> getWorldYear(string c3)
        {
            var c3Parameter = c3 != null ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getWorldYear_Result>("getWorldYear", c3Parameter);
        }
    
        public virtual ObjectResult<getWorldGDP_Result> getWorldGDP(Nullable<int> year, string cc, string c3, string output)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var ccParameter = cc != null ?
                new ObjectParameter("cc", cc) :
                new ObjectParameter("cc", typeof(string));
    
            var c3Parameter = c3 != null ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(string));
    
            var outputParameter = output != null ?
                new ObjectParameter("output", output) :
                new ObjectParameter("output", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getWorldGDP_Result>("getWorldGDP", yearParameter, ccParameter, c3Parameter, outputParameter);
        }
    }
}
